language: python
python:
  - 3.7
  - 3.8
dist: bionic
cache:
  pip: true
  apt: true
matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: LINT_TEST=1
    - python: 3.8
      env: LINT_TEST=1
env:
  - INTEGRATION_TEST=1
  - UNIT_TEST=1
addons:
  apt:
    packages:
    - libgnutls28-dev
    - libjpeg-progs
    - libimage-exiftool-perl
    - gifsicle
    - scons
    - python-all-dev
    - libboost-python-dev
    - libexiv2-dev
    - ffmpeg
install:
  - pip install --upgrade pip
  - pip install poetry
  - cd $TRAVIS_BUILD_DIR && make setup
  - pip install coveralls
before_script:
  - cd $TRAVIS_BUILD_DIR && make redis
script:
  - make ci_test
notifications:
  slack:
    secure: Sf6TJa/H3mq+RGqpLwKNRpNw0YQKX3+5bt5e37CSs8rOC+SoFHVNr29QhbXFPwmqQuy9qKb0t5rzChDIIvXErywU2lEw3/JlQtCt1xLsoUfpBF8g8ldoy6ESO2j9Jj6Y/M/4RN2zN3AAd5gfXPrdLHa++eiRaiAXXU+9ZvtUxuc=
after_success:
  coveralls
