#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	if ! getent passwd thumbor | grep -q thumbor; then
		useradd --system --user-group --home /var/lib/thumbor thumbor
	fi

	install -d -o thumbor -g thumbor -m 750 /var/cache/thumbor

	if [ ! -e /etc/thumbor.key ] ; then
		umask 077
		od --read-bytes 16 --output-duplicates \
			--address-radix n --format x2 /dev/urandom | tr -d ' ' > /etc/thumbor.key
		umask 002
		chown thumbor:thumbor /etc/thumbor.key
	fi
fi

#DEBHELPER#

exit 0
